/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univdb;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.util.logging.*;
import javax.swing.table.*;
import java.sql.ResultSet;

/**
 *
 * @author Mohsin
 */
public class Student_MANAGE extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst1,pst2,pst3;
    Statement st;
    ResultSet rs;
    DefaultTableModel dtm;
    /**
     * Creates new form Student_DELETE
     */
    public Student_MANAGE() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        try{
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/mosu?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","mosu","mosu");
              JOptionPane.showMessageDialog(null,"DataBase Connected");
        }catch(ClassNotFoundException e){
           Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, e); 
        }catch(SQLException e){
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        smd1 = new javax.swing.JButton();
        sm3 = new javax.swing.JTextField();
        smd2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        smd5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sm1 = new javax.swing.JTextField();
        smd3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        smd4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sm2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sm7 = new javax.swing.JTextField();
        sm6 = new javax.swing.JComboBox<>();
        sm5 = new javax.swing.JComboBox<>();
        sm4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("SECTION");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("EMAIL");

        smd1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        smd1.setText("VIEW RECORDS");
        smd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smd1ActionPerformed(evt);
            }
        });

        sm3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        sm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm3ActionPerformed(evt);
            }
        });

        smd2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        smd2.setText("DELETE RECORD");
        smd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smd2ActionPerformed(evt);
            }
        });

        table1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG ID", "NAME", "EMAIL", "DEPARTMENT", "YEAR", "SECTION", "ROLL NO."
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        smd5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        smd5.setText("GO BACK");
        smd5.setActionCommand("GO BACK");
        smd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smd5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("DEPARTMENT");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("REG ID");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("ROLL NO");

        sm1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        smd3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        smd3.setText("UPDATE RECORD");
        smd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smd3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("NAME");

        smd4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        smd4.setText("RESET");
        smd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smd4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("YEAR");

        sm2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        sm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm2ActionPerformed(evt);
            }
        });

        sm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm7ActionPerformed(evt);
            }
        });

        sm6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        sm5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        sm4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "MECH", "ETC" }));
        sm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sm3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sm1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sm2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sm7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(smd4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(smd1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(smd2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(smd3)
                        .addGap(89, 89, 89)
                        .addComponent(smd5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(sm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sm6))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addComponent(smd4)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smd1)
                            .addComponent(smd2)
                            .addComponent(smd3)
                            .addComponent(smd5))
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smd1ActionPerformed
        // TODO add your handling code here:
        try{
            pst1 = con.prepareStatement("select * from student",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            rs = pst1.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
            int cols = rsmd.getColumnCount();
            String colname[] = new String[cols];
            for(int i=1;i<=cols;i++){
                colname[i-1] = rsmd.getColumnName(i);
            }
            int rows = 0;
            while(rs.next()){
                rows++;
            }
            String data[][]=new String[rows][cols];
            rs.beforeFirst();
            rows = 0;
            while(rs.next()){
                for(int i=1;i<=cols;i++){
                    data[rows][i-1] = rs.getString(i);
                }
                rows++;
                DefaultTableModel dtm = new DefaultTableModel(data,colname);
                table1.setModel(dtm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_smd1ActionPerformed

    private void smd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smd2ActionPerformed
        // TODO add your handling code here:
        int i=table1.getSelectedRow();
        try{
            
            dtm = (DefaultTableModel)table1.getModel();
            int r = Integer.parseInt(dtm.getValueAt(i,0).toString());
            pst2 = con.prepareStatement("DELETE FROM `student` WHERE `regid`='"+r+"'");
            sm1.setText(dtm.getValueAt(i,0).toString());
            sm2.setText(dtm.getValueAt(i,1).toString());
            sm3.setText(dtm.getValueAt(i,2).toString());
            sm4.setSelectedItem(dtm.getValueAt(i,3).toString());
            sm5.setSelectedItem(dtm.getValueAt(i,4).toString());
            sm6.setSelectedItem(dtm.getValueAt(i,5).toString());
            sm7.setText(dtm.getValueAt(i,6).toString());
            int re = pst2.executeUpdate();
            if(re>=1){
                int input=JOptionPane.showConfirmDialog(null,"Do You really want to DELETE?","Confirmation",JOptionPane.YES_NO_OPTION);
                if(input == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(null,"Data Deleted");
                }
                else{
                    return;
                }
                dtm.removeRow(i);
                sm2.setText(null);
                sm3.setText(null);
                sm4.setSelectedIndex(0);
                sm5.setSelectedIndex(0);
                sm6.setSelectedIndex(0);
                sm7.setText(null);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_smd2ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int i = table1.getSelectedRow();
        try{
            dtm = (DefaultTableModel)table1.getModel();
            pst3 = con.prepareStatement("select * from student where regid=?");
            pst3.setString(1,sm1.getText());
           
            sm1.setText(dtm.getValueAt(i,0).toString());
            sm2.setText(dtm.getValueAt(i,1).toString());
            sm3.setText(dtm.getValueAt(i,2).toString());
            sm4.setSelectedItem(dtm.getValueAt(i,3).toString());
            sm5.setSelectedItem(dtm.getValueAt(i,4).toString());
            sm6.setSelectedItem(dtm.getValueAt(i,5).toString());
            sm7.setText(dtm.getValueAt(i,6).toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_table1MouseClicked

    private void smd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smd5ActionPerformed
        // TODO add your handling code here:
        Menu h2=new Menu();
        h2.setVisible(true);
        h2.pack();
        h2.setLocationRelativeTo(null);
        h2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_smd5ActionPerformed

    private void smd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smd3ActionPerformed
        // TODO add your handling code here:
 
        try{
            
           String query = ("UPDATE `student` SET `name1`=?,`email1`=?,`depart`=?,`year`=?,`section1`=?,`roll1`=? WHERE `regid`=?");
           con = DriverManager.getConnection("jdbc:mysql://localhost/mosu?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","mosu","mosu");
              
            pst1 = con.prepareStatement(query);
            pst1.setString(1,sm1.getText());
            pst1.setString(2,sm2.getText());
            pst1.setString(3,sm3.getText());
            pst1.setString(4,(String)sm4.getSelectedItem());
            pst1.setString(5,(String)sm5.getSelectedItem());
            pst1.setString(6,(String)sm6.getSelectedItem());
            pst1.setString(7, sm7.getText());

            int r1=pst1.executeUpdate();
            if(r1>=1){
                JOptionPane.showMessageDialog(this, "Updated Successfully");
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,"ERROR ENCOUNTERED");
 }
    }//GEN-LAST:event_smd3ActionPerformed

    private void smd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smd4ActionPerformed
        // TODO add your handling code here:
                sm1.setText(null);
                sm2.setText(null);
                sm3.setText(null);
                sm4.setSelectedIndex(0);
                sm5.setSelectedIndex(0);
                sm6.setSelectedIndex(0);
                sm7.setText(null);
    }//GEN-LAST:event_smd4ActionPerformed

    private void sm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sm7ActionPerformed

    private void sm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sm2ActionPerformed

    private void sm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sm4ActionPerformed

    private void sm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_MANAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_MANAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_MANAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_MANAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_MANAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sm1;
    private javax.swing.JTextField sm2;
    private javax.swing.JTextField sm3;
    private javax.swing.JComboBox<String> sm4;
    private javax.swing.JComboBox<String> sm5;
    private javax.swing.JComboBox<String> sm6;
    private javax.swing.JTextField sm7;
    private javax.swing.JButton smd1;
    private javax.swing.JButton smd2;
    private javax.swing.JButton smd3;
    private javax.swing.JButton smd4;
    private javax.swing.JButton smd5;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
